module.exports = {
  HTTP_STATUS_BAD_REQUEST: 400,
  HTTP_STATUS_NOT_FOUND: 404,
  HTTP_STATUS_INTERNAL_SERVER_ERROR: 500,
  HTTP_STATUS_OK: 200,
  HTTP_STATUS_CREATED: 201,

  MESSAGE_BAD_REQUEST: `Bad request`,
  MESSAGE_NOT_FOUND: `Not found`,
  MESSAGE_INTERNAL_SERVER_ERROR: `Internal server error`,
};
